---
- hosts: docker
  become: true
  tasks:
  - name: Update the repositories
    apt:
     update_cache: yes

  - name: Create /etc/apt/keyrings directory
    command: install -m 0755 -d /etc/apt/keyrings

  - name: Download and install Docker GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  - name: Run command to set permissions
    command: chmod a+r /etc/apt/keyrings/docker.gpg

  - name: Run command to add Docker repository
    shell: |
        echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update the repositories
    apt:
     update_cache: yes

  - name: Install the docker packages
    apt:
     name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
     state: present

  - name: Enable the docker service
    systemd:
     name: docker
     enabled: true

  - name: Start the docker service
    service:
     name: docker
     state: started

  - name: user add into docker group
    command: usermod -aG docker ubuntu
...

